# Generated by Django 5.2.4 on 2026-07-21 21:16

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('fleet', '0002_unaccent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='Número')),
                ('status', models.CharField(choices=[('borrador', 'Borrador'), ('emitida', 'Emitida'), ('anulada', 'Anulada')], db_index=True, default='borrador', max_length=20)),
                ('exchange_rate', models.DecimalField(decimal_places=6, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))], verbose_name='Tasa factura')),
                ('base_imponible_ves', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('iva_ves', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('total_ves', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('total_retenciones_ves', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('total_a_pagar_ves', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('calculation_snapshot', models.JSONField(blank=True, default=dict)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='pdfs/invoices/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_type', models.CharField(choices=[('service', 'Servicio'), ('supply', 'Suministro'), ('embedded_supply', 'Suministro embebido')], db_index=True, max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_price_usd', models.DecimalField(decimal_places=2, max_digits=18)),
                ('cost_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('unit_price_ves', models.DecimalField(decimal_places=2, max_digits=18)),
                ('line_total_ves', models.DecimalField(decimal_places=2, max_digits=18)),
                ('is_embedded', models.BooleanField(default=False)),
                ('is_billable', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.invoice')),
            ],
            options={
                'verbose_name': 'Línea de factura',
                'verbose_name_plural': 'Líneas de factura',
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='Número')),
                ('status', models.CharField(choices=[('borrador', 'Borrador'), ('enviado', 'Enviado'), ('aceptado', 'Aceptado'), ('facturado', 'Facturado'), ('anulado', 'Anulado'), ('confirmar_presupuesto_factura_anulada', 'Confirmar tras factura anulada')], db_index=True, default='borrador', max_length=40)),
                ('exchange_rate', models.DecimalField(decimal_places=6, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))], verbose_name='Tasa presupuesto')),
                ('subtotal_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('iva_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('total_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('notes', models.TextField(blank=True, default='')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='pdfs/quotes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='fleet.truck', verbose_name='Camión')),
            ],
            options={
                'verbose_name': 'Presupuesto',
                'verbose_name_plural': 'Presupuestos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='quote',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='billing.quote', verbose_name='Presupuesto'),
        ),
        migrations.CreateModel(
            name='QuoteLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_type', models.CharField(choices=[('service', 'Servicio'), ('supply', 'Suministro'), ('embedded_supply', 'Suministro embebido')], db_index=True, max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('cost_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('unit_price_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('is_embedded', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('parent_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='embedded_lines', to='billing.quoteline')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.quote')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.service')),
                ('supply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.supply')),
            ],
            options={
                'verbose_name': 'Línea de presupuesto',
                'verbose_name_plural': 'Líneas de presupuesto',
                'ordering': ['sort_order', 'pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='billing_quoteline_quantity_positive')],
            },
        ),
    ]
