# Generated by Django 5.2.4 on 2026-07-22 20:23

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='quote_kind',
            field=models.CharField(choices=[('services', 'Servicios'), ('supplies', 'Suministros')], db_index=True, default='services', max_length=20, verbose_name='Tipo de presupuesto'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, help_text='Tasa de cambio del Banco Central (USD→VES) vigente para este presupuesto.', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))], verbose_name='Tasa BCV presupuesto'),
        ),
    ]
