# Generated by Django 5.2.4 on 2026-07-23 16:37

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_quote_quote_kind_alter_quote_exchange_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='iva_pct',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.1600'), help_text='Fracción decimal copiada desde la empresa al crear; editable solo en este documento.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='IVA del presupuesto (%)'),
        ),
        migrations.CreateModel(
            name='QuoteFiscalRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Código')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('percentage', models.DecimalField(decimal_places=6, help_text='Fracción decimal, ej. 0.75 = 75%.', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='Porcentaje')),
                ('base', models.CharField(choices=[('iva', 'Sobre IVA'), ('base_imponible', 'Sobre base imponible')], max_length=20, verbose_name='Base')),
                ('applies_to', models.CharField(choices=[('service', 'Servicios'), ('supply', 'Suministros'), ('both', 'Ambos')], default='both', max_length=20, verbose_name='Aplica a')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_rules', to='billing.quote', verbose_name='Presupuesto')),
            ],
            options={
                'verbose_name': 'Regla fiscal del presupuesto',
                'verbose_name_plural': 'Reglas fiscales del presupuesto',
                'ordering': ['sort_order', 'code'],
                'constraints': [models.UniqueConstraint(fields=('quote', 'code'), name='billing_quotefiscalrule_quote_code_uniq')],
            },
        ),
    ]
