# Generated by Django 5.2.4 on 2026-07-21 21:16

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(default='MJ SINO IMPORT, C.A.', max_length=255, verbose_name='Razón social')),
                ('rif', models.CharField(default='G-20013109-8', max_length=20, verbose_name='RIF')),
                ('fiscal_address', models.TextField(blank=True, default='', verbose_name='Dirección fiscal')),
                ('iva_pct', models.DecimalField(decimal_places=4, default=Decimal('0.1600'), help_text='Fracción decimal, ej. 0.16 = 16%.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='IVA (%)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de empresa',
                'verbose_name_plural': 'Configuración de empresa',
            },
        ),
        migrations.CreateModel(
            name='FiscalRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('percentage', models.DecimalField(decimal_places=6, help_text='Fracción decimal, ej. 0.75 = 75%.', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='Porcentaje')),
                ('base', models.CharField(choices=[('iva', 'Sobre IVA'), ('base_imponible', 'Sobre base imponible')], max_length=20, verbose_name='Base')),
                ('applies_to', models.CharField(choices=[('service', 'Servicios'), ('supply', 'Suministros'), ('both', 'Ambos')], default='both', max_length=20, verbose_name='Aplica a')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Regla fiscal',
                'verbose_name_plural': 'Reglas fiscales',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_kind', models.CharField(choices=[('quote', 'Presupuesto'), ('invoice', 'Factura')], max_length=20)),
                ('year', models.PositiveIntegerField()),
                ('prefix', models.CharField(max_length=10)),
                ('padding', models.PositiveSmallIntegerField(default=5)),
                ('next_number', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Secuencia de documento',
                'verbose_name_plural': 'Secuencias de documentos',
                'ordering': ['-year', 'document_kind'],
                'constraints': [models.UniqueConstraint(fields=('document_kind', 'year'), name='core_documentsequence_kind_year_uniq')],
            },
        ),
    ]
