# Generated by Django 5.2.4 on 2026-07-22 20:23

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='default_cost_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Costo interno USD (referencia)'),
        ),
        migrations.AddField(
            model_name='service',
            name='default_unit_price_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Se sugiere al crear el presupuesto; el usuario puede confirmarlo o cambiarlo.', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Precio cliente USD (referencia)'),
        ),
        migrations.AddField(
            model_name='supply',
            name='default_cost_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Costo interno USD (referencia)'),
        ),
        migrations.AddField(
            model_name='supply',
            name='default_unit_price_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Se sugiere al crear el presupuesto; el usuario puede confirmarlo o cambiarlo.', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Precio cliente USD (referencia)'),
        ),
    ]
