# Generated by Django 5.2.4 on 2026-07-22 21:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_service_default_cost_usd_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDefaultEmbed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_quantity', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Cantidad por defecto')),
                ('default_cost_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Costo interno USD por defecto')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_embeds', to='catalog.service', verbose_name='Servicio')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='default_for_services', to='catalog.supply', verbose_name='Suministro')),
            ],
            options={
                'verbose_name': 'Suministro embebido por defecto',
                'verbose_name_plural': 'Suministros embebidos por defecto',
                'ordering': ['supply__name'],
                'constraints': [models.UniqueConstraint(fields=('service', 'supply'), name='catalog_servicedefaultembed_service_supply_uniq')],
            },
        ),
    ]
