# Generated by Django 5.2.4 on 2026-07-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_service_default_embed'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='price_updated_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Se actualiza al cambiar precio o costo de referencia.', null=True, verbose_name='Precio actualizado'),
        ),
        migrations.AddField(
            model_name='supply',
            name='price_updated_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Se actualiza al cambiar precio o costo de referencia.', null=True, verbose_name='Precio actualizado'),
        ),
    ]
