# Generated by Django 5.2.4 on 2026-07-21 20:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Nombre completo')),
                ('phone', models.CharField(blank=True, default='', max_length=30, verbose_name='Teléfono')),
                ('id_document', models.CharField(blank=True, db_index=True, default='', max_length=30, verbose_name='Cédula / documento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Conductor',
                'verbose_name_plural': 'Conductores',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rif', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='RIF')),
                ('legal_name', models.CharField(max_length=255, verbose_name='Razón social / nombre')),
                ('fiscal_address', models.TextField(verbose_name='Dirección fiscal')),
                ('phone', models.CharField(blank=True, default='', max_length=30, verbose_name='Teléfono')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Propietario',
                'verbose_name_plural': 'Propietarios',
                'ordering': ['legal_name'],
            },
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Placa')),
                ('brand', models.CharField(max_length=100, verbose_name='Marca')),
                ('model', models.CharField(max_length=100, verbose_name='Modelo')),
                ('vin', models.CharField(blank=True, db_index=True, default='', max_length=32, verbose_name='VIN')),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2100)], verbose_name='Año')),
                ('truck_type', models.CharField(choices=[('basura', 'Basura'), ('cesta', 'Cesta'), ('otro', 'Otro')], db_index=True, default='otro', max_length=20, verbose_name='Tipo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trucks', to='fleet.driver', verbose_name='Conductor / responsable')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trucks', to='fleet.owner', verbose_name='Propietario')),
            ],
            options={
                'verbose_name': 'Camión',
                'verbose_name_plural': 'Camiones',
                'ordering': ['plate'],
                'constraints': [models.CheckConstraint(condition=models.Q(('year__gte', 1950), ('year__lte', 2100)), name='fleet_truck_year_range'), models.UniqueConstraint(condition=models.Q(('vin', ''), _negated=True), fields=('vin',), name='fleet_truck_vin_unique_when_set')],
            },
        ),
    ]
